# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


# creat a sequence
a = 1
b = 2
c = a + b
count = 0
t = [2]
while c < 4000000:
    c = a + b
    k = c % 2
    if k == 0:
        t.append(c)
    a = b
    b = c
    count = count + 1

print(sum(t))
